### ISSUE TITLE
Missing Pose/Predictor.cpp

### ISSUE THREAD

**Issue by ghost** [SEU-SuperNova-CVRA/Robomaster2018-SEU-OpenSource#2]
Hello! First of all, very impressive code. However, when building Robomaster2018.pro with qmake, it fails due to an inability to find <ROOT_DIR>/Pose/Predictor.cpp. I was wondering if this was an issue with the .pro file, or perhaps a missing file? Any help you can provide would be much appreciated!

**Comment by HendrickZhou** [comment]
Predictor.cpp is yet to be completed.  We preserve this for the further algorithm development. So it's totally OK to comment this line in the .pro file.
We actually have explained that in the README.md in Pose (in Chinese lol). Now we 're working on the readmes for an English version, you 'll see it soon!

**Comment by ghost** [comment]
Gotcha! I was working off a google-translated readme file, which would explain the confusion. I'll be sure to try and build it with the necessary comment. Thanks for the fast reply!
